### ISSUE TITLE
zone shapes not generating

### ISSUE THREAD

**Issue by Pranava202004** [AdrianPanGithub/HoudiniMassTranslator#1]
zone shapes not generating also changes made to roaad param is not changing in screen
![Screenshot 2024-12-15 163031](https://github.com/user-attachments/assets/27df6827-e905-40d7-b2a5-872a4b73c584)

**Comment by ChildAdrian** [comment]
I can see you are doing the right thing, this may be an issue, would you like to have a google meeting?https://meet.google.com/wgj-euxi-ipx

**Comment by ChildAdrian** [comment]
As we just learned, the Houdini Engine does NOT support "Apprentice License". so I'll close this issue.

**Comment by Pranava202004** [comment]
Thank you for your help i really mean it i downloaded full version of houdini and now it is working
